### ISSUE TITLE
can't figure out how to build, always error

### ISSUE THREAD

**Issue by FlicksDaModdle** [dillongoostudios/goo-blender#4]
help, it doesn't work somewhere in the process

**Comment by TiredHobgoblin** [comment]
You'll need to provide more information than that if you want to get help, at the very least the actual error you're getting. I'm having issues with building as well: OpenJPEG doesn't seem to be linked properly, the build process isn't able to locate the include files for it, and after fixing that (probably in the wrong way) by copying the includes to the spot where it's looking for them, it runs into an issue location OpenCOLLADA's `xml.lib` file, which I found was missing from the `lib` directory after running `make update`.

**Comment by SerenoV7** [comment]
> You'll need to provide more information than that if you want to get help, at the very least the actual error you're getting. I'm having issues with building as well: OpenJPEG doesn't seem to be linked properly, the build process isn't able to locate the include files for it, and after fixing that (probably in the wrong way) by copying the includes to the spot where it's looking for them, it runs into an issue location OpenCOLLADA's `xml.lib` file, which I found was missing from the `lib` directory after running `make update`.

Same issue for me and I can't find a prebuilt version of that lib

**Comment by Lateasusual** [comment]
Sorry, the build script was still set to use the precompiled libs for 3.2 not 3.3. It should work now

**Comment by SerenoV7** [comment]
> Sorry, the build script was still set to use the precompiled libs for 3.2 not 3.3. It should work now

I just recloned the project and it still gives me the same error
Also gonna mention that `\source\blender\imbuf\intern\` is still missing openjpg.h and other files from the openjpeg library

**Comment by Lateasusual** [comment]
I've merged 3.3 release again, there were also a few changes to library versions in there (including openjpeg) which should be fixed.

**Comment by SerenoV7** [comment]
tried again, still failing to build
This is my [Build.log](https://github.com/dillongoostudios/goo-engine/files/9952861/Build.log)

**Comment by xxxmf** [comment]
> tried again, still failing to build This is my [Build.log](https://github.com/dillongoostudios/goo-engine/files/9952861/Build.log)

make sure to run "make update" before the make

**Comment by FlicksDaModdle** [comment]
it always crashes and stops on buildinfo.c 
after i ran make update and nmake

**Comment by xxxmf** [comment]
for windows:

step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding to path then "make update" wont work
step 2: clone into an empty folder. make sure you are not cloning into a folder that contains files or folders from any other blender version.
step 3: run "make update" TWICE
step 4: run "make" not nmake
step 5: if something errors and above steps dont fix it then delete everything and start over

there is really not much to it. i just built it 30 min ago and it worked fine

**Comment by letsblazelbc** [comment]
> step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding to path then "make update" wont work step 2: clone into an empty folder. make sure you are not cloning into a folder that contains files or folders from any other blender version. step 3: run "make update" TWICE step 4: run "make" not nmake step 5: if something errors and above steps dont fix it then delete everything and start over
> 

I have all the requirements downloaded using the "blender build" page. I download the goo engine zip. files... Extract files into a separate folder on C: drive.  Then I open CMD and type run.  then I press cd "and folder name"  , then type "make update" is that correct so far ?  I am lost after that .  I would appreciate any help , thanks in advance.

**Comment by xxxmf** [comment]
> > step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding to path then "make update" wont work step 2: clone into an empty folder. make sure you are not cloning into a folder that contains files or folders from any other blender version. step 3: run "make update" TWICE step 4: run "make" not nmake step 5: if something errors and above steps dont fix it then delete everything and start over
> 
> I have all the requirements downloaded using the "blender build" page. I download the goo engine zip. files... Extract files into a separate folder on C: drive. Then I open CMD and type run. then I press cd "and folder name" , then type "make update" is that correct so far ? I am lost after that . I would appreciate any help , thanks in advance.

no dont download zip, cd to your empty folder and use "git clone https://github.com/dillongoostudios/goo-engine.git" then cd into the new folder that it makes and run make update twice and wait for any downloads each time and then run make. if it asks to download libraries just type "y" and press enter

**Comment by letsblazelbc** [comment]
appreciate the reply and info @xxxmf .At the end, when I click the application launcher I get "the application has failed to start because its side by side configuration is incorrect. Please see the event log or use command-line sxctrace.exe toll for more details."

**Comment by xxxmf** [comment]
looks like the repository is actually broken again, i am unable to build today. maybe its because of original 3.3 commit idk

**Comment by 0nvd0** [comment]
im not really a programmer but looking into the error i managed to make it compile by replacing this file from the goo engine repository `https://github.com/dillongoostudios/goo-engine/blob/goo-blender-master/extern/audaspace/include/devices/DeviceManager.h` with the one from the blender repository ( `https://github.com/blender/blender/blob/master/extern/audaspace/include/devices/DeviceManager.h` ). im sure the comments on that can give a better explaination than me on why it works and why it doesnt.

**Comment by Lateasusual** [comment]
That audaspace issue is a compiler bug in newer versions of visual studio, but it's not being fixed in 3.3-release since the release happened before MSVC update. We'll update to 3.4 when that's done in a month or so, so I'm just going to leave it as is for now. In the meantime either use a different MSVC version or manually apply that fix from master.

**Comment by letsblazelbc** [comment]
> That audaspace issue is a compiler bug in newer versions of visual studio, but it's not being fixed in 3.3-release since the release happened before MSVC update. We'll update to 3.4 when that's done in a month or so, so I'm just going to leave it as is for now. In the meantime either use a different MSVC version or manually apply that fix from master.

Thank You , I rolled back to the 2019 community version and it worked now !  Thank you guys for the help , I will be donating to the patreon !

**Comment by a-notperson** [comment]
> That audaspace issue is a compiler bug in newer versions of visual studio, but it's not being fixed in 3.3-release since the release happened before MSVC update. We'll update to 3.4 when that's done in a month or so, so I'm just going to leave it as is for now. In the meantime either use a different MSVC version or manually apply that fix from master.

I'm getting the same "the application has failed to start because its side by side configuration is incorrect. Please see the event log or use command-line sxctrace.exe toll for more details." error. I also ran into an issue where it will say
`A    C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15\zstd\include\zstd_errors.h
A    C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15\xr_openxr_sdk\include\openxr\openxr_reflection.h
A    C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15\wintab\include\wintab.h
A    C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15\xr_openxr_sdk\lib\openxr_loader.lib
A    C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15\xr_openxr_sdk\lib\openxr_loaderd.lib
U   C:\Users\irush\Documents\Blender-Goo-Engine\lib\win64_vc15
Checked out revision 63190.
Updating '.':
At revision 63190.
python not found, required for this operation`

This appears after running "make update" then typing "y". Could these two be related and if so would you happen to know how to fix this?

**Comment by TBarbosaMarcelo** [comment]
> > That audaspace issue is a compiler bug in newer versions of visual studio, but it's not being fixed in 3.3-release since the release happened before MSVC update. We'll update to 3.4 when that's done in a month or so, so I'm just going to leave it as is for now. In the meantime either use a different MSVC version or manually apply that fix from master.
> 
> I'm getting the same "the application has failed to start because its side by side configuration is incorrect. Please see the event log or use command-line sxctrace.exe toll for more details." error. I also ran into an issue where it will say "python not found, required for this operation". Which appears after running "make update" then typing "y". Could these two be related and if so would you happen to know how to fix this?

Im having a similar issue, "make update" shows the "python not found" after building, and in my build log I have multiple "fatal error C1083: no such file or directory has been found"

**Comment by Sonario007** [comment]
> for windows:
> 
> step 1: make sure all the requirements are properly installed, if you skipped any instruction like adding to path then "make update" wont work step 2: clone into an empty folder. make sure you are not cloning into a folder that contains files or folders from any other blender version. step 3: run "make update" TWICE step 4: run "make" not nmake step 5: if something errors and above steps dont fix it then delete everything and start over
> 
> there is really not much to it. i just built it 30 min ago and it worked fine

Did all of that but now i have a different problem. When i try to open the application, it says that the side by side config is incorrect. In addition to that, i got 2 errors during the compiling phase. The first one was about **warning C4100: "con"**, calling it an unreferenced formal parameter. The second one read **D:\blender-git\goo-engine\source\blender\editors\object\object_constraint.cc(2294,15): error C7555:** and said that the use of a designated initialiser requires at least **"/std:c++20"**. I'll try compiling the program again with VC 2019.
